FROM ghcr.io/cirruslabs/flutter:3.29.3

USER root

RUN apt-get update && apt-get install -y \
    ruby ruby-dev build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN gem install bundler

WORKDIR /app

COPY Gemfile Gemfile.lock .bundle/ ./
RUN bundle config set --local path vendor/bundle && bundle install

COPY . .

ENTRYPOINT ["bundle", "exec", "fastlane"]
