// Mocks generated by Mockito 5.4.6 from annotations
// in betelapp/test/data/services/content_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:betelapp/core/connectivity_service.dart' as _i6;
import 'package:betelapp/core/database_helper.dart' as _i7;
import 'package:betelapp/data/models/manifest.dart' as _i2;
import 'package:betelapp/data/services/remote_content_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContentManifest_0 extends _i1.SmartFake
    implements _i2.ContentManifest {
  _FakeContentManifest_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteContentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteContentService extends _i1.Mock
    implements _i4.RemoteContentService {
  MockRemoteContentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ContentManifest> fetchManifest() =>
      (super.noSuchMethod(
            Invocation.method(#fetchManifest, []),
            returnValue: _i5.Future<_i2.ContentManifest>.value(
              _FakeContentManifest_0(
                this,
                Invocation.method(#fetchManifest, []),
              ),
            ),
          )
          as _i5.Future<_i2.ContentManifest>);

  @override
  _i5.Future<void> downloadFile({
    required String? remotePath,
    required String? localPath,
    void Function(int, int)? onProgress,
    Duration? stallTimeout = const Duration(seconds: 3),
    int? maxRetries = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [], {
              #remotePath: remotePath,
              #localPath: localPath,
              #onProgress: onProgress,
              #stallTimeout: stallTimeout,
              #maxRetries: maxRetries,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i6.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isMobileData() =>
      (super.noSuchMethod(
            Invocation.method(#isMobileData, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i7.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i5.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i5.Future<_i3.Database>);
}
